version: '3'

vars:
  APP: setup

tasks:
  
  new:
    cmd:
      - cargo new ${APP_NAME} 

  clean:
    cmd:
      - cargo clean

  build:
    cmds:
      - cargo build 

  doc:
    desc: generate rust doc
    cmds:
      - cargo doc

  run:
    desc: run 
    cmds:
      - cargo run
  
  run-binary:
    desc: run binary
    cmds:
      - task clean
      - task build
      - ./target/debug/${APP_NAME}
