version: '3.6'

services:
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
    env_file: .env # https://code.visualstudio.com/docs/remote/containers-advanced
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  dynamodblocal:
    image: amazon/dynamodb-local
    networks:
      - default
    ports:
      - 8000:8000
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb

  dynamodbadmin:
    image: instructure/dynamo-local-admin
    networks:
      - default
    ports:
      - 8001:8001
    environment:
      DYNAMO_ENDPOINT: http://dynamodblocal:8000/
